### ISSUE TITLE
Feature: Users can see the board with the pieces

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the board with all of the pieces
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user starts a game, the board and pieces will render in their correct position.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="238" alt="Screen Shot 2021-11-01 at 5 50 59 PM" src="https://user-images.githubusercontent.com/88172055/139769434-50ffec92-ee98-4b1d-a54d-48af77569c16.png">
<img width="429" alt="Screen Shot 2021-11-01 at 5 51 09 PM" src="https://user-images.githubusercontent.com/88172055/139769439-4c06565f-136e-4f05-9e4b-098a2d0ff1b9.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a server directory containing index.js
- [x] Set up initial requirements for middlewares and express

### ⚡ Client

- [x] Create HTML skeleton with nav bar on top
- [x] Create CSS for visual configuration of HTML
- [x] Create a component to represent the squares
- [x] Create a component to represent the board containing square components
- [x] Render the initial board with the squares
- [x] Create a component to represent the pieces
- [x] Give the components initial positioning and render them in the correct locations
- [x] Append the board to the index.html

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
