### ISSUE TITLE
Feature: Users can choose a color to play as

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose a color to play as
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

At the start of the game, a module will pop up prompting the user to choose a color to play as. Once the user click on one of the top options, the game set the user as the player of that color and allow them to interact with their respective pieces.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="244" alt="Screen Shot 2021-11-05 at 11 29 55 AM" src="https://user-images.githubusercontent.com/88172055/140561239-9d79c9d1-7ade-44f1-ae8d-a4c658463c0f.png">

<img width="657" alt="Screen Shot 2021-11-05 at 11 30 09 AM" src="https://user-images.githubusercontent.com/88172055/140561250-37d544f9-2c97-49c3-8a47-361049738a7b.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a modal component to appear at the beginning of the game
- [x] Style the modal component
- [x] Change the 'color' state of the player to the correct one when a color is clicked
- [x] Set the not chosen color to be the color of the second player
- [x] Remove the module from view once color is chosen
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
