### ISSUE TITLE
Feature: User can move pieces to legal squares

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can move pieces to legal squares
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user select a piece that is their color, the legal squares that it can move to is marked by a green dot. The user can then press on a legal square and the piece will move there.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="332" alt="Screen Shot 2021-11-12 at 11 13 15 AM" src="https://user-images.githubusercontent.com/88172055/141522470-9bcf684b-8573-4701-b972-1e14f209b757.png">
<img width="429" alt="Screen Shot 2021-11-12 at 11 13 39 AM" src="https://user-images.githubusercontent.com/88172055/141522473-a932c979-5320-4755-94fc-00be6fed4a1e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` listen for socket event from client for an update in pieces position on the board.
- [ ] On the event, emit to all clients an event that the position data has been changed and that the the other client's ""isCurrentlyTurn" is now to be set to true.

### ⚡ Client

- [x] Create a "isCurrentlyTurn" property to see if it is current player's turn.
- [x] Create position data for pieces in each piece state.
- [x] Create a "selected" state for the piece if its currently selected.
- [x] Check for legal squares to move to and mark non occupied legal squares with green square
- [x] Update the position for the piece in the state position array for the Board component once moved.
- [x] If the position array is updated, emit an event to the server to emit an update event to other client
- [ ] Change the "isCurrentlyTurn" property to false.
- [ ] Create a socket listener to listen from the server for board changes and if it is now the player's turn
- [ ] Re-render the board with the pieces in the updated positions
### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
